# 2  serviços a serem construidos e mantidos:
    # Aplicação
    # testes
# talvez ter uma imagem do servidor

version: '3'
services:
    composer:
        build:
            context: .
            dockerfile: dockerfile-composer
        command: composer install
        volumes:
            - ./app/wallet:/src/app/
        working_dir: /src/app/
    app:
        build:
            context: .
            dockerfile: dockerfile-app
        ports: 
            - 8000:8000
        expose:
            - 8000
        volumes:
            - ./app/wallet:/src/app/
        depends_on:
            - composer
            - database
        links:
            - database
    database:
        image: mysql:8.0.30
        command: --innodb-use-native-aio=0
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: techchallenge
            MYSQL_ALLOW_EMPTY_PASSWORD: true
        volumes:
            - "./docker/dbdata:/var/lib/mysql"
        


    # tests:
    #     image: php:8.1-cli
    #     restart: "no"
    #     volumes:
    #         - ./:/src/app
    #     working_dir: /src/app
    #     entrypoint: vendor/bin/phpunit
    #     depends_on: 
    #         - composer
